
package UniqueAirlines;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class Seats extends javax.swing.JFrame {

    public Seats() {
        initComponents();
        
        Toolkit tool = getToolkit();
        Dimension size = tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        a1 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        e1 = new javax.swing.JButton();
        f1 = new javax.swing.JButton();
        g1 = new javax.swing.JButton();
        h1 = new javax.swing.JButton();
        i1 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        i3 = new javax.swing.JButton();
        h3 = new javax.swing.JButton();
        g3 = new javax.swing.JButton();
        f3 = new javax.swing.JButton();
        e3 = new javax.swing.JButton();
        d3 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        i2 = new javax.swing.JButton();
        h2 = new javax.swing.JButton();
        g2 = new javax.swing.JButton();
        f2 = new javax.swing.JButton();
        e2 = new javax.swing.JButton();
        d2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        a1.setBackground(new java.awt.Color(0, 255, 255));
        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        a1.setText("A1");
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a1MouseEntered(evt);
            }
        });
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(0, 255, 255));
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        b1.setText("B1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        c1.setBackground(new java.awt.Color(0, 255, 255));
        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        c1.setText("C1");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        d1.setBackground(new java.awt.Color(0, 255, 255));
        d1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        d1.setText("D1");
        d1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d1MouseClicked(evt);
            }
        });

        e1.setBackground(new java.awt.Color(0, 255, 255));
        e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        e1.setText("E1");
        e1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e1MouseClicked(evt);
            }
        });

        f1.setBackground(new java.awt.Color(0, 255, 255));
        f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        f1.setText("F1");
        f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1MouseClicked(evt);
            }
        });

        g1.setBackground(new java.awt.Color(0, 255, 255));
        g1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        g1.setText("G1");
        g1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1MouseClicked(evt);
            }
        });

        h1.setBackground(new java.awt.Color(0, 255, 255));
        h1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        h1.setText("H1");

        i1.setBackground(new java.awt.Color(0, 255, 255));
        i1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        i1.setText("I1");

        a3.setBackground(new java.awt.Color(0, 255, 255));
        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        a3.setText("A3");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        i3.setBackground(new java.awt.Color(0, 255, 255));
        i3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        i3.setText("I3");
        i3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i3ActionPerformed(evt);
            }
        });

        h3.setBackground(new java.awt.Color(0, 255, 255));
        h3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        h3.setText("H3");

        g3.setBackground(new java.awt.Color(0, 255, 255));
        g3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        g3.setText("G3");

        f3.setBackground(new java.awt.Color(0, 255, 255));
        f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        f3.setText("F3");
        f3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f3MouseClicked(evt);
            }
        });

        e3.setBackground(new java.awt.Color(0, 255, 255));
        e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        e3.setText("E3");
        e3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e3MouseClicked(evt);
            }
        });

        d3.setBackground(new java.awt.Color(0, 255, 255));
        d3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        d3.setText("D3");
        d3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d3MouseClicked(evt);
            }
        });

        c3.setBackground(new java.awt.Color(0, 255, 255));
        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        c3.setText("C3");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(0, 255, 255));
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        b3.setText("B3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        a2.setBackground(new java.awt.Color(0, 255, 255));
        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        a2.setText("A2");
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
        });

        i2.setBackground(new java.awt.Color(0, 255, 255));
        i2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        i2.setText("I2");

        h2.setBackground(new java.awt.Color(0, 255, 255));
        h2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        h2.setText("H2");

        g2.setBackground(new java.awt.Color(0, 255, 255));
        g2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        g2.setText("G2");

        f2.setBackground(new java.awt.Color(0, 255, 255));
        f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        f2.setText("F2");
        f2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f2MouseClicked(evt);
            }
        });

        e2.setBackground(new java.awt.Color(0, 255, 255));
        e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        e2.setText("E2");
        e2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e2MouseClicked(evt);
            }
        });

        d2.setBackground(new java.awt.Color(0, 255, 255));
        d2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        d2.setText("D2");
        d2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d2MouseClicked(evt);
            }
        });

        c2.setBackground(new java.awt.Color(0, 255, 255));
        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        c2.setText("C2");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(0, 255, 255));
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/rsz_images.png"))); // NOI18N
        b2.setText("B2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seat Planing");

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniqueAirlines/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1)
                    .addComponent(c1)
                    .addComponent(d1)
                    .addComponent(e1)
                    .addComponent(f1)
                    .addComponent(g1)
                    .addComponent(h1)
                    .addComponent(i1)
                    .addComponent(a1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c2)
                    .addComponent(d2)
                    .addComponent(e2)
                    .addComponent(f2)
                    .addComponent(g2)
                    .addComponent(h2)
                    .addComponent(i2)
                    .addComponent(b2)
                    .addComponent(a2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b3)
                    .addComponent(c3)
                    .addComponent(d3)
                    .addComponent(e3)
                    .addComponent(f3)
                    .addComponent(g3)
                    .addComponent(h3)
                    .addComponent(i3)
                    .addComponent(a3))
                .addGap(20, 20, 20))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
//        this.setVisible(false);
//        new Fligth().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void i3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i3ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
         JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         c2.setBackground(Color.red);
    }//GEN-LAST:event_c2ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
        a1.setBackground(Color.red);
    }//GEN-LAST:event_a1ActionPerformed

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
        a2.setBackground(Color.red);
    }//GEN-LAST:event_a2MouseClicked

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
         JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         a3.setBackground(Color.red);
    }//GEN-LAST:event_a3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
         JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         b1.setBackground(Color.red);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
         JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         b2.setBackground(Color.red);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         b3.setBackground(Color.red);
    }//GEN-LAST:event_b3ActionPerformed

    private void a1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseEntered
        
    }//GEN-LAST:event_a1MouseEntered

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        
    }//GEN-LAST:event_a1MouseClicked

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
         JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         c1.setBackground(Color.red);
    }//GEN-LAST:event_c1ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
         JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         c3.setBackground(Color.red);
    }//GEN-LAST:event_c3ActionPerformed

    private void d1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         d1.setBackground(Color.red);
    }//GEN-LAST:event_d1MouseClicked

    private void d2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         d2.setBackground(Color.red);
    }//GEN-LAST:event_d2MouseClicked

    private void d3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d3MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         d3.setBackground(Color.red);
    }//GEN-LAST:event_d3MouseClicked

    private void e1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         e1.setBackground(Color.red);
    }//GEN-LAST:event_e1MouseClicked

    private void e2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2MouseClicked
       JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         e2.setBackground(Color.red);
    }//GEN-LAST:event_e2MouseClicked

    private void e3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3MouseClicked
       JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         e3.setBackground(Color.red);
    }//GEN-LAST:event_e3MouseClicked

    private void f1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         f1.setBackground(Color.red);
    }//GEN-LAST:event_f1MouseClicked

    private void f2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         f2.setBackground(Color.red);
    }//GEN-LAST:event_f2MouseClicked

    private void f3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         f3.setBackground(Color.red);
    }//GEN-LAST:event_f3MouseClicked

    private void g1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1MouseClicked
        JOptionPane.showMessageDialog(null,"A One Seat Booked ");
         g1.setBackground(Color.red);
    }//GEN-LAST:event_g1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton d1;
    private javax.swing.JButton d2;
    private javax.swing.JButton d3;
    private javax.swing.JButton e1;
    private javax.swing.JButton e2;
    private javax.swing.JButton e3;
    private javax.swing.JButton f1;
    private javax.swing.JButton f2;
    private javax.swing.JButton f3;
    private javax.swing.JButton g1;
    private javax.swing.JButton g2;
    private javax.swing.JButton g3;
    private javax.swing.JButton h1;
    private javax.swing.JButton h2;
    private javax.swing.JButton h3;
    private javax.swing.JButton i1;
    private javax.swing.JButton i2;
    private javax.swing.JButton i3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
